<?xml version="1.0"?>

<robot name="kitchen_description" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Define data here, to make poses & dimensions easily adjustable from the outside -->
  <xacro:property name="data" value="${load_yaml('$(find suturo_perception_msgs)/config/semantic_map_without_opencv_annotation.yaml')}" />

  <xacro:property name="table_x" 
    value="${data['robocup_table']['transform']['data'][3] - table_depth/2}" />
  <xacro:property name="table_y" 
    value="${data['robocup_table']['transform']['data'][7] - table_width/2}" />
  <xacro:property name="table_z_rot" 
    value="${data['robocup_table']['z_rot']}" />
  <xacro:property name="table_depth" 
    value="${data['robocup_table']['depth']}" />
  <xacro:property name="table_width" 
    value="${data['robocup_table']['width']}" />
  <xacro:property name="table_height" 
    value="${data['robocup_table']['height']}" />
  <xacro:property name="shelf_x" 
    value="-${shelf_width}" />
  <xacro:property name="shelf_y" value="0.0" />
  <xacro:property name="shelf_z_rot" value="${pi * 1.5}" />
  <xacro:property name="shelf_depth" value="0.3" />
  <xacro:property name="shelf_width" value="0.99" />
  <xacro:property name="shelf_height" value="1.5" />
  <xacro:property name="shelf_floors_height" value="[0.06, 0.247, 0.80, 1.162, 1.478]" />

  <link name="env_origin"/> 
  
  <xacro:include filename="$(find iai_hsr_robocup)/urdf/HSR_table.urdf.xacro"/>
  <robocup_table name="table" parent="env_origin" size_x="${table_depth}" size_y="${table_width}" size_z="${table_height}" >
    <origin xyz="${table_x} ${table_y} 0.0" rpy="0 0 ${table_z_rot}" />
  </robocup_table>

  <xacro:include filename="$(find iai_hsr_robocup)/urdf/HSR_shelf.urdf.xacro"/>
  <robocup_shelf name="shelf" parent="env_origin" 
    size_x="${shelf_depth}" size_y="${shelf_width}" size_z="${shelf_height}" floors_height="${shelf_floors_height}">
    <origin xyz="${shelf_x} ${shelf_y} 0.0" rpy="0 0 ${shelf_z_rot}" />
  </robocup_shelf>

  
 
</robot>
