<?xml version="1.0"?>

<robot name="robocup_shelf" xmlns:xacro="http://ros.org/wiki/xacro">

  <material name="shelf_grey">
    <color rgba="0.7 0.7 0.8 1"/>
  </material>



  <macro name="robocup_shelf" params="name parent *origin size_x size_y size_z floors_height">
    
    <!-- General conveinience links -->
    <link name="${name}_origin"/>
    <link name="${name}_center"/>
    <link name="${name}_base_center"/>

    <joint name="${name}_origin_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_origin"/>
    </joint>

    <joint name="${name}_center_joint" type="fixed">
      <origin xyz="${size_x/2} ${size_y/2} ${size_z/2}" rpy="0 0 0" />
      <parent link="${name}_origin"/>
      <child link="${name}_center"/>
    </joint> 

    <joint name="${name}_base_center_joint" type="fixed">
      <origin xyz="${size_x/2} ${size_y/2} 0.0" rpy="0 0 0" />
      <parent link="${name}_origin"/>
      <child link="${name}_base_center"/>
    </joint> 


    <!-- WALLS -->
    <robocup_shelf_piece name="${name}_back" parent="${name}_origin" 
      size_x="0.08" size_y="${size_y}" size_z="${size_z}">
      <origin xyz="${size_x} ${size_y/2} ${size_z/2}" rpy="0 0 0"/>
    </robocup_shelf_piece>

    <robocup_shelf_piece name="${name}_right_side" parent="${name}_origin" 
      size_x="${size_x}" size_y="0.01" size_z="${size_z}">
      <origin xyz="${size_x/2} 0.0 ${size_z/2}" rpy="0 0 0"/>
    </robocup_shelf_piece>

    <robocup_shelf_piece name="${name}_left_side" parent="${name}_origin" 
      size_x="${size_x}" size_y="0.01" size_z="${size_z}">
      <origin xyz="${size_x/2} ${size_y} ${size_z/2}" rpy="0 0 0"/>
    </robocup_shelf_piece>


    <!-- FLOORS -->
    <robocup_shelf_piece name="${name}_floor_0" parent="${name}_base_center" 
      size_x="${size_x}" size_y="${size_y}" size_z="0.04">
      <origin xyz="0.0 0.0 ${floors_height[0] - 0.02}" rpy="0 0 0"/>
    </robocup_shelf_piece>

    <robocup_shelf_piece name="${name}_floor_1" parent="${name}_base_center" 
      size_x="${size_x}" size_y="${size_y}" size_z="0.04">
      <origin xyz="0.0 0.0 ${floors_height[1] - 0.02}" rpy="0 0 0"/>
    </robocup_shelf_piece>

    <robocup_shelf_piece name="${name}_floor_2" parent="${name}_base_center" 
      size_x="${size_x}" size_y="${size_y}" size_z="0.04">
      <origin xyz="0.0 0.0 ${floors_height[2] - 0.02}" rpy="0 0 0"/>
    </robocup_shelf_piece>

    <robocup_shelf_piece name="${name}_floor_3" parent="${name}_base_center" 
      size_x="${size_x}" size_y="${size_y}" size_z="0.04">
      <origin xyz="0.0 0.0 ${floors_height[3] - 0.02}" rpy="0 0 0"/>
    </robocup_shelf_piece>

    <robocup_shelf_piece name="${name}_floor_4" parent="${name}_base_center" 
      size_x="${size_x}" size_y="${size_y}" size_z="0.04">
      <origin xyz="0.0 0.0 ${floors_height[4] - 0.02}" rpy="0 0 0"/>
    </robocup_shelf_piece>
  </macro>



  <!-- Creates a link with collision and visual box of given dimensions,
  and a respective joint to append it to the parent with given origin.  -->
  <macro name="robocup_shelf_piece" params="name parent *origin size_x size_y size_z">

    <!-- LINK -->
    <link name="${name}_piece">
      <visual>
        <material name="shelf_grey"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${size_x} ${size_y} ${size_z}" />
        </geometry>
      </collision>
    </link>

    <!-- JOINT -->
    <joint name="${name}_piece_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_piece"/>
    </joint>
  </macro>


</robot>